plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
      dead-code-detection: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - test/**
